# -*- ruby -*-

require 'rubygems'
require 'bundler/setup'
require 'rjack-tarpit'

RJack::TarPit.new( 'gravitext-xmlprod' ) do |tp|
  tp.rdoc_destinations <<
    'dekellum@rubyforge.org:/var/www/gforge-projects/gravitext/gravitext-xmlprod'
end
