# -*- ruby -*-
#--
# Copyright (C) 2008 David Kellum
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#++

require 'rubygems'
require 'hoe'

$LOAD_PATH << './lib'

ENV['NODOT'] = "no thank you"

require 'gravitext-xmlprod/version' 

jars = [ "gravitext-xmlprod-#{Gravitext::XMLProd::VERSION}.jar",
         "jdom-1.1.jar" ]

jar_files = jars.map { |jar| "lib/gravitext-xmlprod/#{jar}" }

desc "Update the Manifest with actual jar"
task :manifest do
  out = File.new( 'Manifest.txt', 'w' ) 
  begin
    out.write <<END
Manifest.txt
README.txt
History.txt
Rakefile
pom.xml
bin/gravitext-xmlprod-perftest
lib/gravitext-xmlprod.rb
lib/gravitext-xmlprod/version.rb
END
    out.puts jar_files
  ensure
    out.close
  end
end


file :mvn => [ 'pom.xml' ] do
  sh( 'mvn package ' + 
      'dependency:copy-dependencies -DincludeArtifactIds=jdom ' +
      '-DoutputDirectory=target' )
end

jars.each do |jar|
  file "lib/gravitext-xmlprod/#{jar}" => [ :mvn ] do
    cp_r( File.join( "target/", jar ), 'lib/gravitext-xmlprod' )
  end
end

[ :gem, :test ].each { |t| task t => ( jar_files ) }

task :mvn_clean do
  rm_f( jar_files )
  sh( 'mvn clean' )
end
task :clean => :mvn_clean 

task :tag do
  tag = "gravitext-xmlprod-#{Gravitext::XMLProd::VERSION}"
  dname = File.dirname( __FILE__ )
  dname = '.' if Dir.getwd == dname
  sh( "git status --only #{dname}" ) do |ok,res|
    raise "Commit these changes before tagging." if ok #changes present
  end
  sh %{git tag -s -f -m "tag [#{tag}]" "#{tag}"}
end

hoe = Hoe.new( "gravitext-xmlprod", Gravitext::XMLProd::VERSION ) do |p|
  p.developer( "David Kellum", "dek-oss@gravitext.com" )
  p.rubyforge_name = "gravitext"
  p.rdoc_pattern = /^(lib.*\.(rb|txt))|[^\/]*\.txt$/
  p.extra_deps << [ 'gravitext-util', '>= 1.3' ]
end
