# -*- ruby -*-

$LOAD_PATH << './lib'
require 'gravitext-util/version'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.4'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'gravitext-util',
                       Gravitext::Util::VERSION,
                       :no_assembly, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )

  h.testlib = :minitest
  h.extra_dev_deps += [ [ 'rjack-slf4j',   '>= 1.5.8',  '< 1.7' ],
                        [ 'rjack-logback', '>= 0.9.18', '< 2.0' ],
                        [ 'minitest',      '~> 2.3'             ] ]

  h.rdoc_locations << "dekellum@rubyforge.org:/var/www/gforge-projects/gravitext/gravitext-util"
end

file 'Manifest.txt' => [ 'lib/gravitext-util/version.rb' ]

task :check_pom_version do
  t.test_line_match( 'pom.xml', /<version>/, /#{t.version}/ )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_version, :check_history_version                      ]
task :tag  => [ :check_pom_version, :check_history_version, :check_history_date ]
task :push => [                                             :check_history_date ]

t.define_tasks
